"""create_initial_tables

Revision ID: f012f11380b2
Revises: 
Create Date: 2026-04-08 16:01:50.702522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f012f11380b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.Enum('SA', 'ZM', name='market_enum'), nullable=False),
    sa.Column('factor_set', sa.Enum('CARD_SA', 'MOBILE_ZM', 'CUSTOM', name='factor_set_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('PILOT', 'STARTER', 'GROWTH', 'SCALE', name='plan_enum'), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('slack_webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('HIGH_RISK_BATCH', 'COLLECTION_RATE_DROP', 'PREDICTION_DRIFT', name='alert_type_enum'), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_tenant_read_created', 'alerts', ['tenant_id', 'is_read', 'created_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_keys_tenant_active', 'api_keys', ['tenant_id', 'is_active'], unique=False)
    op.create_table('score_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=False),
    sa.Column('external_collection_id', sa.String(length=255), nullable=False),
    sa.Column('collection_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collection_currency', sa.Enum('ZAR', 'ZMW', name='collection_currency_enum'), nullable=False),
    sa.Column('collection_due_date', sa.Date(), nullable=False),
    sa.Column('collection_method', sa.Enum('CARD', 'DEBIT_ORDER', 'MOBILE_MONEY', name='collection_method_enum'), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_requests_tenant_collection', 'score_requests', ['tenant_id', 'external_collection_id'], unique=False)
    op.create_index('ix_score_requests_tenant_created', 'score_requests', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_score_requests_tenant_customer', 'score_requests', ['tenant_id', 'external_customer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('factor_weights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('factor_name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'factor_name', name='uq_factor_weight_tenant_factor')
    )
    op.create_table('score_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score_request_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level_enum'), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=False),
    sa.Column('recommended_collection_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('scoring_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_request_id'], ['score_requests.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_request_id')
    )
    op.create_index('ix_score_results_tenant_created', 'score_results', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_score_results_tenant_risk', 'score_results', ['tenant_id', 'risk_level'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score_result_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_collection_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='outcome_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('failure_category', sa.Enum('SOFT_DECLINE', 'HARD_DECLINE', 'TECHNICAL', name='failure_category_enum'), nullable=True),
    sa.Column('amount_collected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_result_id')
    )
    op.create_index('ix_outcomes_score_result', 'outcomes', ['score_result_id'], unique=False)
    op.create_index('ix_outcomes_tenant_outcome', 'outcomes', ['tenant_id', 'outcome'], unique=False)
    op.create_index('ix_outcomes_tenant_reported', 'outcomes', ['tenant_id', 'reported_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outcomes_tenant_reported', table_name='outcomes')
    op.drop_index('ix_outcomes_tenant_outcome', table_name='outcomes')
    op.drop_index('ix_outcomes_score_result', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('ix_score_results_tenant_risk', table_name='score_results')
    op.drop_index('ix_score_results_tenant_created', table_name='score_results')
    op.drop_table('score_results')
    op.drop_table('factor_weights')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_score_requests_tenant_customer', table_name='score_requests')
    op.drop_index('ix_score_requests_tenant_created', table_name='score_requests')
    op.drop_index('ix_score_requests_tenant_collection', table_name='score_requests')
    op.drop_table('score_requests')
    op.drop_index('ix_api_keys_tenant_active', table_name='api_keys')
    op.drop_index('ix_api_keys_key_prefix', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_alerts_tenant_read_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('tenants')
    # ### end Alembic commands ###
